AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GreenmoOpenMapsApiToken:
    Type: String
  GreenmoDomainName:
    Type: String
  GreenmoCertificateArn:
    Type: String

Resources:
  GreenMoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GreenMoUsagePlan
          Description: "Usage plan for GreenMo API"
      BinaryMediaTypes:
        - image~1png
      Cors:
        AllowMethods: "'GET,OPTIONS'"
      Domain:
        DomainName: !Ref GreenmoDomainName
        CertificateArn: !Ref GreenmoCertificateArn
        EndpointConfiguration: REGIONAL
        SecurityPolicy: TLS_1_2

  ChargableCarsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./function/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 15
      Environment:
        Variables:
          GREENMO_OPEN_MAPS_API_TOKEN: !Ref GreenmoOpenMapsApiToken
      Events:
        QueryApi:
          Type: Api
          Properties:
            Path: /query
            Method: GET
            RestApiId: !Ref GreenMoApi

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${GreenMoApi}.execute-api.${AWS::Region}.amazonaws.com/prod/query"
