name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'template.yaml'
      - 'run.sh'
      - 'deploy.sh'
      - 'function/**'
      - '.github/workflows/**'

permissions:
  id-token: write   # Required for JWT
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'function/go.mod'
          cache-dependency-path: 'function/go.sum'

      - name: Run tests
        run: |
          ./run.sh test

      - name: Setup AWS SAM CLI
        run: |
          curl -LO "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip"
          unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
          sudo ./sam-installation/install
          sam --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.GREENMO_AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.GREENMO_AWS_ACCOUNT }}:role/greenmo-stalker-oidc
          role-session-name: greenmo-oidc-action-session

      - name: Build and deploy
        run: |
          ./deploy.sh
        env:
          GREENMO_AWS_REGION: ${{ vars.GREENMO_AWS_REGION }}
          GREENMO_OPEN_MAPS_API_TOKEN: ${{ secrets.GREENMO_OPEN_MAPS_API_TOKEN }}
          GREENMO_DOMAIN_NAME: ${{ vars.GREENMO_DOMAIN_NAME }}
          GREENMO_CERTIFICATE_ARN: ${{ vars.GREENMO_CERTIFICATE_ARN }}
