name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'template.yaml'
      - 'run.sh'
      - 'deploy.sh'
      - 'function/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Run tests
        run: |
          ./run.sh test

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build and deploy
        run: sam build --use-container

      - name: SAM Deploy
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name greenmo-stalker-stack \
            --region ${{ vars.GREENMO_AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
                MapsApiToken=${{ secrets.GREENMO_OPEN_MAPS_API_TOKEN }} \
                ApiKey=${{ secrets.GREENMO_API_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GREENMO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GREENMO_AWS_SECRET_ACCESS_KEY }}